site_name: Documentazione Partner AAS
docs_dir: docs

# Configurazione del tema
theme:
  name: material
  language: it
  palette:
    primary: indigo
    accent: blue
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - toc.follow

# Plugin attivi
plugins:
  - search

# markdown_extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences