site_name: Partner DevDocs
theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: false
      type: datetime
      timezone: Europe/Rome
