name: Deploy MkDocs
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Pulisce gli spazi invisibili e sposta i file .md e la cartella immagini dentro docs
      - run: |
          find . -maxdepth 1 -name "*.md" -exec sed -i 's/\xc2\xa0/ /g' {} \;
          mkdir -p docs
          find . -maxdepth 1 -name "*.md" -exec mv {} docs/ \;
          if [ -d "immagini" ]; then mv immagini docs/; fi
      
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
